public enum SoundEvent
{
    SeedPlanted,
    SeedHarvested,
    PlantReady,
    ItemBought,
    ItemSold,
    ShopOpened,
    ShopClosed,
    PlotPlaced,
    PlotRemoved,
    PlotWatered,
    InsufficientFunds,
    InventoryFull,
    NoSeedSelected,
    MutationOccurred,
    WateringCan,
    UIClick,
    DialogueOpen,
    DialogueClose,
    FertilizerApplied
}
